article/urls.py
from django.contrib import admin
from django.urls import path,re_path
from . import views
app_name="article"

urlpatterns=[
    path("dashboard/",views.dashboard,name="dashboard"),
    path("createarticle/",views.createarticle,name="createarticle"),
    path("article/<int:id>",views.article.as_view(),name="article"),
    path("update/<int:id>",views.update.as_view(),name="update"),
    path("delete/<int:id>",views.deleteArticle,name="delete"),
    path("",views.articles,name="articles"),
    re_path(r'^update/(?P<id>\d+)/$', views.update.as_view())
    
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from article import views
from django.conf.urls import handler404,handler403,handler500
from article import views 
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.index,name="index"),  
    path("about/",views.about,name="about"),
    path("detail/<int:id>/",views.detail,name="detail"),
    path("articles/",include("article.urls")),
    path("user/",include("user.urls")),
    path("api/",include("article.api.urls")),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),

    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    
]
handler403 = views.error_403
handler404 = views.error_404
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "user"


urlpatterns=[
    path("register/",views.register,name="register"),
    path("login/",views.loginn,name="login"),
    path("logout/",views.logoutt,name="logout"),
    path("userpage/<int:id>",views.user_page.as_view(),name="user_page")

]

templates/includes/navbar.html
<nav class="navbar navbar-dark" style="background-color: #581845;">
  <a class="navbar-brand" href="{% url 'index'%}" style="color:rgb(0, 0, 0);"><h2>𝕏Article</h2></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}" style="color:{{request.user.last_name}};">{% if request.user.username %} {{request.user.username}}'s {% endif %}Home <span class="sr-only">(current)</span></a>
      </li>
      {% if not request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{%url 'user:register'%}">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'user:login'%}">Login</a>
      </li>
      {% endif %}
      <li class="nav-item dropdown">
        <a type="button" href="{%url 'article:dashboard'%}" class="btn btn-outline-warning">Go to dashboard</a>
        <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dash Board of Article 
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{%url 'article:dashboard'%}">Go to Dashboard</a>
          <a class="dropdown-item" href="{%url 'article:createarticle'%}">Create Article</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" style="background-color: red;" href="{%url 'article:dashboard'%}">Delete articles</a>
        </div>
      </li>
      <li class="nav-item active">
        <a class="nav-link disabled" href="{%url 'article:articles'%}">Search others Article</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{%url 'about' %}">About Us <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'user:logout'%}">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">by kerem</a>
        </li>
      </ul>
  </div>
</nav>

templates/includes/not_found_article.html
<!DOCTYPE html>
{% load static %}
<html>
<head>

  <meta charset="UTF-8">
  <title>Not Found PAGE</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
  
      <link rel="stylesheet" href="{% static 'css/style2.css' %}">
  
</head>
 <body>
    

<div id="app">
   {% block Message %} 
   <div>Article Not Found</div>
    <div class="txt">
    Hey Try Again for Search<span class="blink">_</span>
    </div>
    {% endblock Message %}
 </div>
</body>
</html>