article/api/urls.py
from django.urls import path
from article.api import views as api_views

#http://www.django-rest-framework.org/api-guide/routers/

# from rest_framework.routers import DefaultRouter

# from article.api.views import UserViewSet
# app_name = "blog"
# router = DefaultRouter()
# router.register("users", UserViewSet)
#CLASS BASED VİEWS
urlpatterns = [
    path("makaleler/",api_views.ArticleListCreateAPIView.as_view(),name="api-listesi"),
    path("makaleler/<int:id>",api_views.ArticleDetailAPIView.as_view(),name="api-articles"),
    path("users/",api_views.UserListCreateAPIView.as_view(),name="user-list")
]   


#FUNCTİON BASED VİEWS
# urlpatterns = [
#     path("/makaleler",api_views.article_list_create_api_view,name="makale-listesi"),
#     path("/makaleler/<int:id>",api_views.article_detail_api_view,name="makale_detay")

# ]

article/urls.py
from django.contrib import admin
from django.urls import path,re_path
from . import views
app_name="article"

urlpatterns=[
    path("dashboard/",views.dashboard,name="dashboard"),
    path("createarticle/",views.createarticle,name="createarticle"),
    path("article/<int:id>",views.article.as_view(),name="article"),
    path("update/<int:id>",views.update.as_view(),name="update"),
    path("delete/<int:id>",views.deleteArticle,name="delete"),
    path("",views.articles,name="articles"),
    re_path(r'^update/(?P<id>\d+)/$', views.update.as_view())
    
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from article import views
from django.conf.urls import handler404,handler403,handler500
from article import views 
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.index,name="index"),  
    path("about/",views.about,name="about"),
    path("detail/<int:id>/",views.detail,name="detail"),
    path("articles/",include("article.urls")),
    path("user/",include("user.urls")),
    path("api/",include("article.api.urls")),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),

    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    
]
handler403 = views.error_403
handler404 = views.error_404
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
# Create your models here.
#https://ceakssan.com/tr/middleware-nedir-ne-ise-yarar
#https://docs.djangoproject.com/en/4.1/topics/http/middleware/
#https://docs.djangoproject.com/en/4.1/ref/models/options/
class Article(models.Model):
                               #"auth.user"
    author = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name="Yazar",related_name="articles") #başka bir tabloyu göstermek istiyorsak Foreign key i kullanmamız gerekiyor,yani burada yazar tablomuzu django'dan hazır user tablosunu çekiyoruz 
                                                            #on_delete'nin anlamı ise user silindiğinde makalenin de silinmesi anlamını veriyor
    
    title = models.CharField(max_length=50,verbose_name="Başlık")
    #content = models.TextField(verbose_name="İçerik")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi") #o anki tarihi direkt olarak atar
    article_image = models.FileField(blank=True,null=True,verbose_name="Makaleye Fotoğraf Ekleyin")
    def __str__(self):
        return self.title
    class Meta:
        ordering =["-created_date"]
    #def clean()
class Hashtags(models.Model):
    author = models.ForeignKey("auth.User",on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    linked_article = models.ForeignKey("article.article",on_delete=models.CASCADE)
    def __str__(self):
        return self.title

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name="Makale",related_name="comments")
    comment_author = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name="isim")
    comment_content = models.CharField(max_length=200,verbose_name="Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering =["-comment_date"]

article/forms.py
from django import forms
#https://docs.djangoproject.com/en/4.1/topics/forms/modelforms/
from .models import Article
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]

article/api/views.py
from  rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view

#class views
from rest_framework.views import APIView

from rest_framework.generics import get_object_or_404

from article.models import Article
from article.api.serializers import ArticleSerializer,UserSerializer
from django.contrib.auth.models import User
#CLASS BASED VİEWS

from rest_framework.viewsets import ModelViewSet

class UserViewSet(ModelViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username" #users/lookup_field

class UserListCreateAPIView(APIView):
    def get(self,request):
        users = User.objects.all()
        serializer = UserSerializer(users,many = True,context={'request':request})#context={'request':request} ekleme sebebimiz ise HyperLinked ekleme anlamı
        return Response(serializer.data)
    
    def post(self,request):
        user = UserSerializer(data =request.data)
        if user.is_valid():
            user.save()
            return Response(user.data,status=status.HTTP_201_CREATED)
        return  Response(user.errors,status=status.HTTP_400_BAD_REQUEST)


class ArticleListCreateAPIView(APIView):
    def get(self,request):
        articles = Article.objects.all()
        serializer = ArticleSerializer(articles,many = True)
        return Response(serializer.data)
    
    def post(self,request):
        article = ArticleSerializer(data =request.data)
        if article.is_valid():
            article.save()
            return Response(article.data,status=status.HTTP_201_CREATED)
        return  Response(article.errors,status=status.HTTP_400_BAD_REQUEST)

class ArticleDetailAPIView(APIView):
    def get_object(self,id):
        article_instance = get_object_or_404(Article,id=id)
        return article_instance
    def get(self,request,id):
        article =self.get_object(id=id)
        serializer = ArticleSerializer(article)
        return Response(serializer.data)
    def put(self,request,id):
        article =self.get_object(id=id)
        serializer = ArticleSerializer(article,data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)
    def delete(self,request,id):
        article =self.get_object(id=id)
        article.delete()  
        return Response(
            {
                "errors": {
                    'code':204,
                    "message": f'{id} adlı numaralı makale silinmiştir'
                } 
            },

            status=status.HTTP_204_NO_CONTENT
        )





#FUNCTİON BASED VİEWS
# @api_view(["GET","POST"])
# def article_list_create_api_view(request):
#     if request.method == "GET":
#         articles = Article.objects.all()
#         serializer = ArticleSerializer(articles,many = True)
#         return Response(serializer.data)
#     else:
#         article = ArticleSerializer(data =request.data)
#         if article.is_valid():
#             article.save()
#             return Response(article.data,status=status.HTTP_201_CREATED)
#         return  Response(status=status.HTTP_400_BAD_REQUEST)
# @api_view(["GET","PUT","DELETE"])
# def article_detail_api_view(request,id):
#     try:
#         article_instance = Article.objects.get(id=id)
#     except Article.DoesNotExist:
#         return Response(
#             {
#                 "errors": {
#                     'code':404,
#                     "message": f'Böyle bir id {id} ile ilgili makale bulunamadı.'
#                 } 
#             },

#             status=status.HTTP_404_NOT_FOUND
#         )
#     if request.method == "GET":
#         serializer = ArticleSerializer(article_instance)
#         return Response(serializer.data)
#     elif request.method == "PUT":
#         serializer = ArticleSerializer(article_instance,data=request.data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response(serializer.data)
#         return Response(status=status.HTTP_400_BAD_REQUEST)  
#     elif request.method == "DELETE": #json da True değil true 
#         article_instance.delete()        #json formatına api/makaleler den bakabiliriz
#         return Response(
#             {
#                 "errors": {
#                     'code':204,
#                     "message": f'{id} adlı numaralı makale silinmiştir'
#                 } 
#             },

#             status=status.HTTP_204_NO_CONTENT
#         )

article/views.py
from functools import wraps
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404
from .models import Article,Comment
from .forms import ArticleForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required,user_passes_test
from django.conf import settings
from django.contrib.auth.mixins import UserPassesTestMixin,LoginRequiredMixin
from  django.views import View
# Create your views here.
#https://startbootstrap.com/template/blog-post
#https://docs.djangoproject.com/en/4.1/topics/auth/
#https://docs.djangoproject.com/en/4.1/topics/http/middleware/

def index(request):
    return render(request,"index.html")

def about(request):
    return render(request,"about.html")

def detail(request,id): 
    return HttpResponse("Detail"+ str(id))

@login_required(login_url="user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)  
    context = {"articles":articles}


    return render(request,"dashboard.html",context)


@login_required(login_url="user:login")
def createarticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"Makale başarıyla oluşturuldu...")
        return redirect("article:dashboard") 
    return render(request,"createarticle.html",{"form":form})



class article(View):
    template_name = "article.html"
    login_url = '/user/login/'
    def get(self,request,id):
        articlee = get_object_or_404(Article,id=id)
        comments = articlee.comments.all()
        return render(request,"article.html",{"article":articlee,"comments":comments})
    def post(self,request,id):
        comment = request.POST.get("comment")
        articlee = get_object_or_404(Article,id=id)
        if comment:Comment.objects.create(article = articlee,comment_author = request.user,comment_content=comment)
        comments = articlee.comments.all()
        return render(request,"article.html",{"article":articlee,"comments":comments})


class update(LoginRequiredMixin,UserPassesTestMixin, View):
    form_class = ArticleForm
    template_name = "update.html"
    login_url = '/user/login/'
    redirect_field_name = '/articles/update/<int:id>'
    def get(self,request,id):
        article = get_object_or_404(Article,id=id)
        self.id = id
        form = self.form_class(instance=article)
        return render(request,self.template_name,{"form":form})
    def post(self,request,id):
        article = get_object_or_404(Article,id=id)
        form = self.form_class(request.POST or None,request.FILES or None,instance=article)
        if form.is_valid():
            article = form.save(commit= False)
            article.author = request.user
            article.save()
            messages.success(request,"Makeleniz Güncellendi...")
            return redirect("article:dashboard")
        return render(request,self.template_name,{"form":form})
    def test_func(self):
        article = get_object_or_404(Article,id=self.kwargs["id"])
        return self.request.user == article.author

    
@login_required(login_url="user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id=id)
    article.delete()
    messages.success(request,"Makale başarıyla silindi!!!")
    return redirect("article:dashboard")


def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    articles = Article.objects.all()
    return render(request,"articles.html",{"articles":articles})

def error_404(request,exception):
    return render(request,'error_404.html',status=404)

def error_403(request,exception):
    return render(request,'error_403.html',status=403)

    

templates/about.html
{% extends 'layout.html' %}

{% block body %}
<div class="jumbotron">
    <h1 class="display-4">Hello, Article User!</h1>
    <p class="lead">Python Css Jss Html Django</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <p class="lead">
      <a class="btn btn-primary btn-lg" href="{%url 'index'%}" role="button">Return Home Page</a>
    </p>
    
    <a href="https://www.linkedin.com/in/kerem-b%C3%B6y%C3%BCk-147890247/">Github</a>
  </div>

{% endblock body %}

templates/article.html
{% extends 'layout.html' %}
<!--https://docs.djangoproject.com/en/4.1/topics/forms/modelforms/-->

{% block body %}
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
            <!-- Post content-->
            <article>
                <!-- Post header-->
                <header class="mb-4">
                    <!-- Post title-->
                    <h1 class="fw-bolder mb-1">{{article.title}}</h1>
                    <!-- Post meta content-->                  
                    <h4><div class="text-muted fst-italic mb-2" style="color:{{request.user.last_name}};"> by {{article.author}}</div></h4>
                    <hr>
                    <h6><div class="text-muted fst-italic mb-2">Posted on {{article.created_date}}</div></h6>
                    <!-- Post categories-->
                    <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
                    <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a>
                </header>
                <!-- Preview image figure-->
                {% if article.article_image %}
                <figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="..." /></figure>
                {% else %}
                <figure class="mb-4"><img class="img-fluid rounded" src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..." /></figure>
                {% endif %}
                <!-- Post content-->
                <section class="mb-5">
                    <p class="fs-5 mb-4">{{article.content|safe}}</p>
                    <p class="fs-5 mb-4">Science is an enterprise that should be cherished as an activity of the free human mind. Because it transforms who we are, how we live, and it gives us an understanding of our place in the universe.</p>
                    <p class="fs-5 mb-4">The universe is large and old, and the ingredients for life as we know it are everywhere, so there's no reason to think that Earth would be unique in that regard. Whether of not the life became intelligent is a different question, and we'll see if we find that.</p>
                    <p class="fs-5 mb-4">If you get asteroids about a kilometer in size, those are large enough and carry enough energy into our system to disrupt transportation, communication, the food chains, and that can be a really bad day on Earth.</p>
                    <h2 class="fw-bolder mb-4 mt-5">I have odd cosmic thoughts every day</h2>
                    <p class="fs-5 mb-4">For me, the most fascinating interface is Twitter. I have odd cosmic thoughts every day and I realized I could hold them to myself or share them with people who might be interested.</p>
                    <p class="fs-5 mb-4">Venus has a runaway greenhouse effect. I kind of want to know what happened there because we're twirling knobs here on Earth without knowing the consequences of it. Mars once had running water. It's bone dry today. Something bad happened there as well.</p>
                </section>
            </article>
            <!-- Comments section-->
                    <section class="mb-5">
                        <div class="card bg-light">
                            <div class="card-body">
                                <!-- Comment form-->
                                <form class="mb-4" method="post">{% csrf_token %}<textarea name="comment" class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea><button type="submit" class="btn btn-outline-warning">Send it</button></form>
                                <!-- Comment with nested comments-->
                                
                                <div class="d-flex mb-4">
                                    <!-- Parent comment-->
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">Saxocu</div>
                                        Sa
                                        <!-- Child comment 2-->
                                        <div class="d-flex mt-4">
                                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                            <div class="ms-3">
                                                <div class="fw-bold">Embesil</div>
                                                As, Site yarram gibi olmuş
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                                {% if comments %}
                                {% for comment in comments %}
                                <div class="d-flex">
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">{{comment.comment_date}} <br>{{request.user.username}}</div>
                                        {{comment.comment_content}}
                                    </div>
                                </div>
                                {% endfor %}
                                {% else %}
                                <div class="d-flex">
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">{{request.user.username}}</div>
                                        İlk yorumu sen yap 
                                    </div>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                    </section>
        </div>
        <!-- Side widgets-->
        <div class="col-lg-4">
            <!-- Search widget-->
            <div class="card mb-4">
                <div class="card-header">Search</div>
                <div class="card-body">
                    <div class="input-group">
                        <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                        <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                    </div>
                </div>
            </div>
            <!-- Categories widget-->
            <div class="card mb-4">
                <div class="card-header">Categories</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <ul class="list-unstyled mb-0">
                                <li><a href="#!">Web Design</a></li>
                                <li><a href="#!">HTML</a></li>
                                <li><a href="#!">Freebies</a></li>
                            </ul>
                        </div>
                        <div class="col-sm-6">
                            <ul class="list-unstyled mb-0">
                                <li><a href="#!">JavaScript</a></li>
                                <li><a href="#!">CSS</a></li>
                                <li><a href="#!">Tutorials</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Side widget-->
            <div class="card mb-4">
                <div class="card-header">Side Widget</div>
                <div class="card-body">İstedini gir</div>
            </div>
        </div>
    </div>
</div>
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="js/scripts.js"></script>
{% endblock body %}

templates/articles.html
{% extends 'layout.html' %}




{% block body %}
<body style="background-color: #444444;">
{% if articles %}

<div class="container" style="margin-top: 100px; margin-bottom:50px;">

    <h2 style="color:darkmagenta;">All Articles</h2>
<hr>
<form >
  {% csrf_token %}
<div class="input-group" style="width: 300px;">
 
  <input name="keyword" type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
  <button type="submit" class="btn btn-outline-primary">search</button>

</div>
</form>
<hr>
<div id="accordion">
    
    <div class="card"  style="background-color:bisque;">
        {% for article in articles  %}
      <div class="card-header" id="headingTwo">
        <h5 class="mb-0">
          <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse{{article.id}}" aria-expanded="false" aria-controls="collapseTwo">
            {{article.title}} #{{article.id}} <a href="" style="color:{{article.author.last_name}};">by {{article.author}}</a>
          </button>
        </h5>
      </div>
      <div id="collapse{{article.id}}" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
        <div class="card-body">
          <p>{% if article.article_image %}
            <img width="300" class="img-fluid rounded" src="{{article.article_image.url}}" alt="..." />
            {% endif %}</p>
          {{article.content|safe|truncatewords:3}}
          <small><a href="{%url 'article:article' article.id %}">Go for More </a></small>
        </div>
      </div>
      {% endfor %}
    </div>
    
</div>
</div>

{% else %}
{% include "includes/not_found_article.html" %}

{% endif %}
{% endblock body %}

templates/createarticle.html
{% extends 'layout.html' %}

{% block body %}
{% load crispy_forms_tags %}

<form class="col-md-6 offset-md-3" method="post" enctype="multipart/form-data">
<br>
<h1>Makale Oluştur</h1>
<hr>
    {% csrf_token %}
    {{form.media}}
    {{form|crispy}}
    <br>
    <button type="submit" class="btn btn-danger">Makale Oluştur</button>
</form>


{% endblock body %}

templates/dashboard.html
{% extends 'layout.html' %}

{% block body %}
<body style="background-color: #444444;">
  <div class="container">
  <br>
    <h3 style="color:aquamarine;">Kontrol Paneli</h3>
<hr>
<p style="color:brown;">Hoşgeldiniz <b style="color:{{request.user.last_name}};">{{request.user.username}}</b></p>
<hr>
<a class="btn btn-danger" href="{% url 'article:createarticle'%}">Makale Ekle</a>
<hr>
<table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Author</th>
        <th scope="col">title</th>
        <th scope="col">Date</th>
        <th scope="col">Update</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
       {% if articles %}
        {% for article in articles %}
        <tr>
          <th scope="row">{{article.id}}</th>
          <td> <a style="color:{{request.user.last_name}};" href="/user/{{article.author.username}}">{{article.author.username}}</a></td>
          <td><a href="{%url 'article:article' article.id %}">{{article.title}}</a></td>
          <td>{{article.created_date}}</td>
          <td><a href="{%url 'article:update' article.id %}" class="btn btn-danger">Update</a></td>
          <td><a href="{%url 'article:delete' article.id %}" class="btn btn-danger">Delete</a></td>
        </tr>
        {% endfor %}
        {% else %}
        <tr><td><div class="container"><a class="btn btn-danger">You don't have an article to view</a></div></td></tr>
        {% endif %}
    </tbody>
  </table>
</div>
{% endblock body %}

templates/error_403.html
<!DOCTYPE html>
{% load static %}
<html>
<head>

  <meta charset="UTF-8">
  <title>403 PAGE</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
  
      <link rel="stylesheet" href="{% static 'css/style2.css' %}">
  
</head>
 <body>
    

<div id="app">
   {% block Message %} 
   <div>403</div>
    <div class="txt">
     This is not your article<span class="blink">_</span>
    </div>
    {% endblock Message %}
 </div>
</body>
</html>

templates/error_404.html
<!DOCTYPE html>
{% load static %}
<html>
<head>

  <meta charset="UTF-8">
  <title>404 PAGE</title>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1">
  
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
  
</head>
 
<body>
  <div id="particles-js">
  <canvas class="particles-js-canvas-el"  style="width: 100%; height: 100%;">
  </canvas>
</div>
 
<div class="container">
  <div class="text">
    <h1 style="text-shadow: -2px 0 0 rgba(255,0,0,.7),
		2px 0 0 rgba(0,255,255,.7);"> {% block whate %} ERROR 404 {% endblock whate %} </h1>
    <p> <a href="#">Go Back</a></p>
  </div>
</div>
    <script  src="{% static 'js/function.js' %}"></script>
</body>
</html>

templates/index.html
{% extends "layout.html" %}

templates/login.html
{% extends 'layout.html' %}


{% block body %}
{% load crispy_forms_tags %}
<!--https://django-crispy-forms.readthedocs.io/en/latest/install.html-->
<!--https://github.com/googlearchive/code-prettify?ysclid=laobl0j2zb191972418-->
<form class="col-md-6 offset-md-3" method="post">
<br>
<h1>Giriş Yap</h1>
<hr>


    {% csrf_token %}
    {{form|crispy}}
    <br>
    <button type="submit" class="btn btn-danger">Giriş Yap</button>
</form>

{% endblock body %}

templates/update.html
{% extends 'layout.html' %}

{% block body %}
{% load crispy_forms_tags %}

<form class="col-md-6 offset-md-3" method="post" enctype="multipart/form-data">
<br>
<h1>Makale Güncelle</h1>
<hr>
    {% csrf_token %}
    {{form.media}}
    {{form|crispy}}
    <br>
    <button type="submit" class="btn btn-danger">Güncelle</button>
</form>


{% endblock body %}